if (!require("ggplot2")) 
  install.packages("ggplot2")
if(!require("quantmod")) 
  install.packages("quantmod")
if(!require("shiny")) 
  install.packages("shiny")
if(!require("rsconnect")) 
  install.packages("rsconnect")

library(shiny)
library(quantmod)
library(ggplot2)
library(rsconnect)

shinyUI(fluidPage(theme="theme.css",
                  tags$head(
                    tags$style(HTML("
                                    h1 { font-weight: 500; line-height: 1.1; }
                                    hr { width: 2px; }
                                    .irs-min, .irs-max {color: #CCC; background-color: #777;}
                                    "))
                    ),
                  headerPanel("Trump Effect"),
                  sidebarPanel(
                    wellPanel(
                      selectInput("tickers", "Symbols:", choices = c("Apple (AAPL)", "Exxon Mobile (XOM)", "J P Morgan (JPM)", "Boeing (BA)"))
                    ),
                    p("Please allow a moment for calculations to complete when you first click on a tab or change the symbol.")
                  ),
                  
                  mainPanel(
                    tabsetPanel(
                      tabPanel("Returns", 
                               # Use multiple conditions to control output
                               conditionalPanel(condition = "input.tickers == 'Apple (AAPL)' ",
                                                div(plotOutput(outputId = "pre_election_news_aapl_return")),
                                                div(plotOutput(outputId = "post_election_news_aapl_return")),
                                                hr()),
                               conditionalPanel(condition = "input.tickers == 'Exxon Mobile (XOM)' ",
                                                div(plotOutput(outputId = "pre_election_news_xom_return")),
                                                div(plotOutput(outputId = "post_election_news_xom_return"))),
                               conditionalPanel(condition = "input.tickers == 'J P Morgan (JPM)' ",
                                                div(plotOutput(outputId = "pre_election_news_jpm_return")),
                                                div(plotOutput(outputId = "post_election_news_jpm_return"))),
                               conditionalPanel(condition = "input.tickers == 'Boeing (BA)' ",
                                                div(plotOutput(outputId = "pre_election_news_ba_return")),
                                                div(plotOutput(outputId = "post_election_news_ba_return")))),
                      tabPanel("C.I.",
                               sliderInput("cilevel", label = h5("Confidence Level %:"), min = 80, max = 99, value = 95, step=1),
                               conditionalPanel(condition = "input.tickers == 'Apple (AAPL)' ",
                                                p(strong("Confidence Intervals")),
                                                br(),
                                                p(strong("AAPL Mean Pre-Trump")),
                                                div(textOutput(outputId = "ci_aapl_pre_election_news")),
                                                br(),
                                                p(strong("AAPL Mean Post-Trump")),
                                                div(textOutput(outputId = "ci_aapl_post_election_news")),
                                                br(),
                                                p(strong("AAPL Var. Pre-Trump")),
                                                div(textOutput(outputId = "ci_var_aapl_pre_election_news")),
                                                br(),
                                                p(strong("AAPL Var. Post-Trump")),
                                                div(textOutput(outputId = "ci_var_aapl_post_election_news")),
                                                hr()),
                               conditionalPanel(condition = "input.tickers == 'Exxon Mobile (XOM)' ",
                                                br(),
                                                p(strong("XOM Mean Pre-Trump")),
                                                div(textOutput(outputId = "ci_xom_pre_election_news")),
                                                br(),
                                                p(strong("XOM Mean Post-Trump")),
                                                div(textOutput(outputId = "ci_xom_post_election_news")),
                                                br(),
                                                p(strong("XOM Var. Pre-Trump")),
                                                div(textOutput(outputId = "ci_var_xom_pre_election_news")),
                                                br(),
                                                p(strong("XOM Var. Post-Trump")),
                                                div(textOutput(outputId = "ci_var_xom_post_election_news"))),
                               conditionalPanel(condition = "input.tickers == 'J P Morgan (JPM)' ",
                                                br(),
                                                p(strong("JPM Mean Pre-Trump")),
                                                div(textOutput(outputId = "ci_jpm_pre_election_news")),
                                                br(),
                                                p(strong("JPM Mean Post-Trump")),
                                                div(textOutput(outputId = "ci_jpm_post_election_news")),
                                                br(),
                                                p(strong("JPM Var. Pre-Trump")),
                                                div(textOutput(outputId = "ci_var_jpm_pre_election_news")),
                                                br(),
                                                p(strong("JPM Var. Post-Trump")),
                                                div(textOutput(outputId = "ci_var_jpm_post_election_news"))),
                               conditionalPanel(condition = "input.tickers == 'Boeing (BA)' ",
                                                br(),
                                                p(strong("BA Mean Pre-Trump")),
                                                div(textOutput(outputId = "ci_ba_pre_election_news")),
                                                br(),
                                                p(strong("BA Mean Post-Trump")),
                                                div(textOutput(outputId = "ci_ba_post_election_news")),
                                                br(),
                                                p(strong("BA Var. Pre-Trump")),
                                                div(textOutput(outputId = "ci_var_ba_pre_election_news")),
                                                br(),
                                                p(strong("BA Var. Post-Trump")),
                                                div(textOutput(outputId = "ci_var_ba_post_election_news")))),
                      tabPanel("Means Comp.",
                               conditionalPanel(condition = "input.tickers == 'Apple (AAPL)' ",
                                                br(),
                                                strong("AAPL Trump Effect Means"),
                                                tableOutput(outputId = "aapl_aapl_means")),
                               conditionalPanel(condition = "input.tickers == 'Exxon Mobile (XOM)'",
                                                br(),
                                                strong("XOM Trump Effect Means"),
                                                tableOutput(outputId = "xom_xom_means")),
                               conditionalPanel(condition = "input.tickers == 'J P Morgan (JPM)'",
                                                br(),
                                                strong("JPM Trump Effect Means"),
                                                tableOutput(outputId = "jpm_jpm_means")),
                               conditionalPanel(condition = "input.tickers == 'Boeing (BA)'",
                                                br(),
                                                strong("BA Trump Effect Means"),
                                                tableOutput(outputId = "ba_ba_means"))),
                      tabPanel("Q-Q", 
                               conditionalPanel(condition = "input.tickers == 'Apple (AAPL)'",
                                                br(),
                                                div(plotOutput(outputId = "qqplot_aapl")),
                                                hr()), 
                               conditionalPanel(condition = "input.tickers == 'Exxon Mobile (XOM)'",
                                                br(),
                                                div(plotOutput(outputId = "qqplot_xom"))),
                               conditionalPanel(condition = "input.tickers == 'J P Morgan (JPM)'",
                                                br(),
                                                div(plotOutput(outputId = "qqplot_jpm"))),
                               conditionalPanel(condition = "input.tickers == 'Boeing (BA)'",
                                                br(),
                                                div(plotOutput(outputId = "qqplot_ba")))),
                      tabPanel("Time Regr.",
                               conditionalPanel(condition = "input.tickers == 'Apple (AAPL)'",
                                                br(),
                                                div(plotOutput(outputId = "reg_onestock_data_plot_aapl")),
                                                hr(),
                                                p('The R-squared of this regression: '),
                                                div(textOutput(outputId = "reg_onestock_r2_aapl")),
                                                hr(),
                                                div(dataTableOutput(outputId = "reg_onestock_coeffs_aapl")),
                                                hr(),
                                                div(plotOutput(outputId = "reg_onestock_resid_plot_aapl")),
                                                hr()),
                               conditionalPanel(condition = "input.tickers == 'Exxon Mobile (XOM)'",
                                                br(),
                                                div(plotOutput(outputId = "reg_onestock_data_plot_xom")),
                                                hr(),
                                                p('The R-squared of this regression: '),
                                                div(textOutput(outputId = "reg_onestock_r2_xom")),
                                                hr(),
                                                div(dataTableOutput(outputId = "reg_onestock_coeffs_xom")),
                                                hr(),
                                                div(plotOutput(outputId = "reg_onestock_resid_plot_xom"))),
                               conditionalPanel(condition = "input.tickers == 'J P Morgan (JPM)' ",
                                                br(),
                                                div(plotOutput(outputId = "reg_onestock_data_plot_jpm")),
                                                hr(),
                                                p('The R-squared of this regression: '),
                                                div(textOutput(outputId = "reg_onestock_r2_jpm")),
                                                hr(),
                                                div(dataTableOutput(outputId = "reg_onestock_coeffs_jpm")),
                                                hr(),
                                                div(plotOutput(outputId = "reg_onestock_resid_plot_jpm"))),
                               conditionalPanel(condition = "input.tickers == 'Boeing (BA)'",
                                                br(),
                                                div(plotOutput(outputId = "reg_onestock_data_plot_ba")),
                                                hr(),
                                                p('The R-squared of this regression: '),
                                                div(textOutput(outputId = "reg_onestock_r2_ba")),
                                                hr(),
                                                div(dataTableOutput(outputId = "reg_onestock_coeffs_ba")),
                                                hr(),
                                                div(plotOutput(outputId = "reg_onestock_resid_plot_ba")))),
                      tabPanel("Index Regr.",
                               conditionalPanel(condition = "input.tickers == 'Apple (AAPL)'",
                                                br(),
                                                plotOutput(outputId = "reg_twostocks_data_plot_aapl_spy"),
                                                hr(),
                                                p('The R-squared of this regression: '),
                                                div(textOutput(outputId = "reg_twostocks_r2_aapl_spy")),
                                                hr(),
                                                div(dataTableOutput(outputId = "reg_twostocks_coeffs_aapl_spy")),
                                                hr(),
                                                plotOutput(outputId = "reg_twostocks_resid_plot_aapl_spy")),
                               conditionalPanel(condition = "input.tickers == 'Exxon Mobile (XOM)'",
                                                br(),
                                                plotOutput(outputId = "reg_twostocks_data_plot_xom_spy"),
                                                hr(),
                                                p('The R-squared of this regression: '),
                                                div(textOutput(outputId = "reg_twostocks_r2_xom_spy")),
                                                hr(),
                                                div(dataTableOutput(outputId = "reg_twostocks_coeffs_xom_spy")),
                                                hr(),
                                                plotOutput(outputId = "reg_twostocks_resid_plot_xom_spy")),
                               conditionalPanel(condition = "input.tickers == 'J P Morgan (JPM)'",
                                                br(),
                                                plotOutput(outputId = "reg_twostocks_data_plot_jpm_spy"),
                                                hr(),
                                                p('The R-squared of this regression: '),
                                                div(textOutput(outputId = "reg_twostocks_r2_jpm_spy")),
                                                hr(),
                                                div(dataTableOutput(outputId = "reg_twostocks_coeffs_jpm_spy")),
                                                hr(),
                                                plotOutput(outputId = "reg_twostocks_resid_plot_jpm_spy")),
                               conditionalPanel(condition = "input.tickers == 'Boeing (BA)'",
                                                br(),
                                                plotOutput(outputId = "reg_twostocks_data_plot_ba_spy"),
                                                hr(),
                                                p('The R-squared of this regression: '),
                                                div(textOutput(outputId = "reg_twostocks_r2_ba_spy")),
                                                hr(),
                                                div(dataTableOutput(outputId = "reg_twostocks_coeffs_ba_spy")),
                                                hr(),
                                                plotOutput(outputId = "reg_twostocks_resid_plot_ba_spy")))
                    )
                  )
))
